export const IMAGES = {
  certifications: {
    udemy: '/certifications/udemy.png',
  },
  education: {
    hust: '/education/hust.png',
  },
  language: {
    circom: '/language/circom.svg',
    'c++': '/language/cplusplus.svg',
    'c#': '/language/csharp.svg',
    'f#': '/language/fsharp.svg',
    go: '/language/go.png',
    java: '/language/java.svg',
    js: '/language/js.webp',
    python: '/language/python.svg',
    solidity: '/language/solidity.svg',
  },
  skill: {
    kafka: '/skills/apache-kafka.png',
    blockchain: '/skills/blockchain.png',
    '.net': '/skills/dotnet.png',
    nestjs: '/skills/nestjs.svg',
    next: '/skills/next.svg',
    react: '/skills/react.svg',
    'spring-boot': '/skills/spring-boot.png',
    vuejs: '/skills/vuejs.png',
  },
  tools: {
    docker: '/tools/docker.svg',
    github: '/tools/github.webp',
    gitlab: '/tools/gitlab.svg',
    latex: '/tools/latex.svg',
    mui: '/tools/materialui.svg',
    mongodb: '/tools/mongodb.svg',
    mysql: '/tools/mysql.svg',
    tailwindcss: '/tools/tailwindcss.svg',
    ts: '/tools/typescript.svg',
    visualstudio: '/tools/visualstudio.svg',
    vscode: '/tools/vscode.svg',
  },
  'dark-sky': '/dark-sky.svg',
  quote: '/quote.svg',
  sharp: '/sharp.svg',
  star: '/favicon.ico',
  thumbnail: '/thumbnail.webp',
};
